services:
  - type: web
    name: igcse-toolkit
    env: python
    plan: standard
    buildCommand: ""
    startCommand: gunicorn server:app --worker-class uvicorn.workers.UvicornWorker --timeout 300
    envVars:
      - key: OPENAI_API_KEY
        sync: false
